[package]
name = "axum_custom_extractors"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = {version = "0.8.8"}
tokio = {version = "1.49.0", features = ["full"]}
tower-http = {version = "0.6.8", features = ["cors"]}
thiserror = {version = "2.0.18"}
tracing = {version = "0.1.44"}
tracing-subscriber = {version = "0.3.22"}
validator = {version = "0.20.0", features = ["derive"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
